services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: hate-ocr-dev
    env_file: .env
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
   